# Generated by Django 5.2.16 on 2026-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversation_options_conversation_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
