# Generated by Django 5.2.16 on 2026-07-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_message_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskHRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('question', models.TextField(help_text="The user's last question in the chat")),
                ('bot_answer', models.TextField(blank=True, help_text='What the bot said (if anything)')),
                ('user_note', models.TextField(blank=True, help_text='Optional extra context from the user')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('retrieved_titles', models.JSONField(blank=True, default=list)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('email_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_hr_requests', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
